config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :podcast_episodes, only: [ :index, :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :podcast_episode
end

app/models/podcast_episode.rb
class PodcastEpisode < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/podcast_episodes_controller.rb
class PodcastEpisodesController < ApplicationController

  def new
    @podcast_episode = PodcastEpisode.new
  end

  def create
    @podcast_episode = PodcastEpisode.new
    @podcast_episode.save!
  end

  def index
    @podcast_episodes = PodcastEpisode.all
  end

  def show
    @podcast_episode = PodcastEpisode.find(params[:id])
  end

  def edit

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/podcast_episodes_helper.rb
module PodcastEpisodesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Database</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Cantarell|Fjalla+One|Work+Sans:300,500" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  </head>

  <body>
    <div class="application-wrapper">
        <%= render partial: "components/sidebar" %>
      <%= yield %>
    </div>
  </body>

</html>

app/views/pages/about.html.erb
<h1>About page</h1>

app/views/pages/home.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="jumbotron home-jumbo">
      <button type="button" id="sidebarCollapse" class="btn btn-yours-minimal">
        <i class="fas fa-align-left"></i>
        <!-- <span >MENU</span> -->
      </button>
      <div class="jumbo-cta">
        <h2> Solve The Future </h2>
        <p class="lead"> Weekly problem-solving podcasts featuring a diverse mix of thought leaders</p>
        <button type="button" class="btn-yours-minimal">
          <span>LISTEN</span>
        </button>
      </div>
      <div class="scroller">
        <div class="chevron"></div>
        <div class="chevron"></div>
        <div class="chevron"></div>
        <!-- <span class="text">Scroll down</span> -->
      </div>
    </div>
  </div>
  <div class="row row-no-padding home-top-content">
    <div class="col-xs-12 col-lg-4 ml-auto">
      <div class="col-xs-12 home-text-content" id="dynamic-margin">
        <div class="d-flex justify-content-start">
          <h1 class="h1-a">Solve The Future</h1>
        </div>
        <div class="d-flex flex-column align-items-end">
          <p style="max-width: 75%">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga incidunt expedita, quo molestias sapiente inventore hic totam consectetur saepe deleniti commodi consequuntur quae, natus error non asperiores quas ut officia.</p>
        </div>
      </div>
      <div class="col-xs-12 home-text-content">
        <div class="d-flex justify-content-start">
          <h1 class="h1-b">Solutions-driven podcasts</h1>
        </div>
        <div class="d-flex flex-column align-items-end">
          <p style="max-width: 75%">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla tenetur esse, sunt, ipsa porro consequatur sequi quibusdam! Quasi similique possimus unde, ad perspiciatis repellat dolores eveniet dolorum doloremque. Dolorem, ratione.</p>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <%= image_tag("stairway-to-ftr") %>
    </div>
  </div>

</div>

<script type="text/javascript">
  // only use this format for desktop
  if (screen.width > 480) {
  // calc height of text divs
  var textItems = document.getElementsByClassName('home-text-content');
  var textHeight = 0
  for (var i = textItems.length - 1; i >= 0; i--) {
    textHeight += textItems[i].clientHeight;
  };
  // set margin-top of text divs row to be (100vh - textHeight)
  document.getElementById('dynamic-margin').style.marginTop = `calc(100vh - ${textHeight}px)`;
  }

</script>

app/views/pages/welcome.html.erb
<div class="container">
  <div class="row row-padded-top">

    <div class="col-xs-12 col-md-5 welcome-title">
      <div class="col-xs-12">
      <h1>Solve</h1>
      </div>
      <div class="col-xs-12">
      <h1>the</h1>
      </div>
      <div class="col-xs-12">
      <h1>future.</h1>
      </div>
    </div>

    <div class="col-xs-12 col-md-7 welcome-subtitle">
      <div class="subtitle-box">
        <h2>SOLUTIONS-DRIVEN PODCASTS</h2>
        <button type="button" class="btn btn-yours">
          <%= link_to 'ENTER', page_path('home') %>
        </button>
      </div>
    </div>
  </div> <!-- row end -->

</div> <!-- container end -->

app/views/podcast_episodes/index.html.erb
<h1> Podcasts_index </h1>

<% @podcast_episodes.each do |episode| %>

<p> <%= link_to "#{episode.title}", podcast_episode_path(episode) %> </p>


<% end %>

app/views/podcast_episodes/show.html.erb
<h1> <%= @podcast_episode.title %> </h1>
<p> <%= @podcast_episode.upload_date %> </p>

<iframe width="50%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="<%= @podcast_episode.url %>"></iframe>